export const SET_ARTICLE =  "SET_ARTICLE";
export const GET_ARTICLE_VIEW = "GET_ARTICLE_VIEW";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const SET_ISEDITING = "SET_ISEDITING"
export const SET_ISOWNER = "SET_ISOWNER"